server:
  port: ${SERVER_PORT:9006}

internal:
  api-key: ${INTERNAL_API_KEY}

exchange:
  ws-host: ${EXCHANGE_WS_HOST}
  api-key: ${EXCHANGE_API_KEY}
  api-secret: ${EXCHANGE_API_SECRET}
  rest-url: ${EXCHANGE_REST_URL:http://localhost:8085}

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:[*],http://127.0.0.1:[*],http://192.168.*.*:[*],http://10.*.*.*:[*],http://172.*.*.*:[*]}
